name: Test Java Formatter Action
on:
  workflow_dispatch:
    inputs:
      gjf-version:
        description: "Google java format version"
        required: true
        default: latest
      asop:
        description: "Use ASOP style"
        required: true
        default: true
      src-path:
        description: "Use ASOP style"
        required: true
        default: src

jobs:
  format-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Build formatter runner
        shell: bash
        run: |
          mkdir -p out
          javac -d out GoogleJavaFormatter.java

      - name: Run formatter runner
        shell: bash
        run: |
          java -cp out GoogleJavaFormatter ${{ inputs.gjf-version }} ${{ inputs.asop }} ${{ inputs.src-path }}

      - name: Commit formatting changes
        shell: bash
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          if git diff --cached --quiet; then
            echo "No changes"
          else
            git commit -m "style(checkstyle): formatted Java files"
            git push